version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      PORT: ${PORT}
      MONGO_URL: ${MONGO_URL}
      DOMAIN_EMAIL_HOST: ${DOMAIN_EMAIL_HOST}
      DOMAIN_EMAIL_PORT: ${DOMAIN_EMAIL_PORT}
      DOMAIN_EMAIL: ${DOMAIN_EMAIL}
      DOMAIN_EMAIL_PASSWORD: ${DOMAIN_EMAIL_PASSWORD}
    networks:
      - shared
  db:
    image: mongo:latest
    networks:
      - shared
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  shared:
